

GET https://3aepqllr4l.execute-api.us-east-2.amazonaws.com/prod/spaces/
###

GET https://3aepqllr4l.execute-api.us-east-2.amazonaws.com/prod/spaces/

#lambda stack

###
GET https://hl9pwjacd6.execute-api.us-east-2.amazonaws.com/prod/spaces

###
POST https://hl9pwjacd6.execute-api.us-east-2.amazonaws.com/prod/spaces



###
POST https://hl9pwjacd6.execute-api.us-east-2.amazonaws.com/prod/spaces
Content-Type: application/json

{
    "location": "california"
}
### 


###
GET https://hl9pwjacd6.execute-api.us-east-2.amazonaws.com/prod/spaces?id=fc17de52-b06d-4b73-88eb-da18cdf4221b

### 